apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-tekton-app
spec:
  replicas: 1
  # This ensures it kills the old one and starts a new one
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: basic-tekton-app
  template:
    metadata:
      labels:
        app: basic-tekton-app
      annotations:
        # Tekton will update this timestamp to force a restart
        last-updated: "1765970174"
    spec:
      containers:
        - name: basic-tekton-app
          image: image-registry.openshift-image-registry.svc:5000/cicd-demo/basic-tekton-app:v2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
